### ISSUE TITLE
Let's use more user-friendly hourCycle for `Test started at`

### ISSUE THREAD

**Issue by gilbok** [wanteddev/lighthouse#9]
`hourCycle:h24` is making this kind of result.

> Test started at: 03/12/2021, 24:33:20

00:33:20 would be better for this.

According to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle
We would better use `h23`.

We just need to modify this line:
https://github.com/wanteddev/lighthouse/blob/e81fd1520a81b41cce301dadfd65502888916199/src/utils/common.js#L28

**Comment by avasconcelos114** [comment]
That's a great idea!
Thank you for the taking the initiative for opening an issue and a PR
